=== katkielbasa/it-love/XML/bin/ex_5_1b/names.dtd
<!ELEMENT osoby (osoba+)>
<!ELEMENT osoba (imie, nazwisko)>
<!ELEMENT imie (#PCDATA)>
<!ELEMENT nazwisko (#PCDATA)>
<!ATTLIST osoba plec (kobieta|mezczyzna|pokemon) #REQUIRED>
<!ATTLIST osoba plec (kobieta|mezczyzna) #REQUIRED>

=== katkielbasa/it-love/XML/src/ex_5_1a/Copy of names.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE osoby SYSTEM "names.dtd">
<osoby>
	<osoba>Jan Kowalski</osoba>
	<osoba />
	<osoba></osoba>
	<osoba>
		<imie>Jan</imie>
		<nazwisko>Kowalski</nazwisko>
	</osoba>
	<osoba>
		<nazwisko>Kowalski</nazwisko>
		<imie>Jan</imie>
	</osoba>
	<osoba>
		Jan Kowalski
		<nazwisko>Kowalski</nazwisko>
		<imie>Jan</imie>
		Ko≈Ñ Przewalskiego
	</osoba>
</osoby>
