=== katkielbasa/it-love/XML/bin/ex_6_2/NewXMLSchema1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="osoby">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="osoba" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="imie" />
							<xs:element type="xs:string" name="nazwisko" />
							<xs:element type="xs:positiveInteger" name="wiek" />
						</xs:sequence>
						<xs:attribute name="plec">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="mezczyzna" />
									<xs:enumeration value="kobieta" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== katkielbasa/it-love/XML/src/ex_6_2/NewFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<osoby xsi:noNamespaceSchemaLocation="NewXMLSchema1.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<osoba plec="mezczyzna">
		<imie>Jan</imie>
		<nazwisko>Kowalski</nazwisko>
		<wiek>23</wiek>
	</osoba>
	<osoba plec="kobieta">
		<imie>Anna</imie>
		<nazwisko>Nowak</nazwisko>
		<wiek>23</wiek>
	</osoba>
</osoby>
